export const matchStatus = {
  SCHEDULED: "계획",
  TIMED: "예정",
  IN_PLAY: "경기중",
  PAUSED: "일시정지",
  EXTRA_TIME: "추가시간",
  PENALTY_SHOOTOUT: "승부차기",
  FINISHED: "종료",
  SUSPENDED: "중단",
  POSTPONED: "연기",
  CANCELLED: "취소",
  AWARDED: "시상",
}

export const teamKorName: any = {
  BHA: "브라이튼",
  ARS: "아스널",
  LIV: "리버풀",
  AVL: "아스톤 빌라",
  MUN: "맨체스터 유나이티드",
  NEW: "뉴캐슬",
  BOU: "본머스",
  BRE: "브렌트포드",
  CRY: "크리스탈 팰리스",
  NOT: "노팅엄",
  CHE: "첼시",
  LEI: "레스터 시티",
  MCI: "맨체스터 시티",
  TOT: "토트넘",
  WHU: "웨스트햄",
  FUL: "풀럼",
  SOU: "사우스햄튼",
  IPS: "입스위치",
  WOL: "울버햄튼",
  EVE: "에버튼",
}

export const teamStadium: any = {
  BHA: "American Express Community Stadium",
  ARS: "Emirates Stadium",
  LIV: "Anfield",
  AVL: "Villa Park",
  MUN: "Old Trafford",
  NEW: "St. James' Park",
  BOU: "Vitality Stadium",
  BRE: "Gtech Community Stadium",
  CRY: "Selhurst Park",
  NOT: "Carrow Road",
  CHE: "Stamford Bridge",
  LEI: "King Power Stadium",
  MCI: "Etihad Stadium",
  TOT: "Tottenham Hotspur Stadium",
  WHU: "London Stadium",
  FUL: "Craven Cottage",
  SOU: "St. Mary's Stadium",
  IPS: "Portman Road",
  WOL: "Molineux Stadium",
  EVE: "Goodison Park",
}
